% Author: Atanu Giri
% Date : 01/13/2023


function jerkOutlierOnInputArray(startRow,endRow)
tic;

% startRow = 1000; endRow = 1005;
loadfile = load('input_data.mat');
input_data = loadfile.input_data;

[id,totalRunningTime,accOutlierMethod1,bigAcceleration,accOutlierMedian,accOutlierMoveMedian,accOutlierMean, ...
    accOutlierQuartiles,accOutlierGrubbs,accOutlierGesd,accOutlierThreshold, ...
    jerkOutlierMethod1,bigJerkness,jerkOutlierMedian,jerkOutlierMoveMedian,jerkOutlierMean, ...
    jerkOutlierQuartiles,jerkOutlierGrubbs,jerkOutlierGesd,jerkOutlierThreshold] ...
    = arrayfun(@(id) jerkOutlierWOPlot(id),input_data.id(startRow:endRow), ...
    'UniformOutput',true,'ErrorHandler',@(S,id)jerkOutlierErrorHandler(S,id));

outputFileName = sprintf('jerkOutlier%dto%d',startRow,endRow);

save(outputFileName,"id","totalRunningTime","accOutlierMethod1","bigAcceleration","accOutlierMedian", ...
    "accOutlierMoveMedian","accOutlierMean",...
    "accOutlierQuartiles","accOutlierGrubbs","accOutlierGesd", ...
    "accOutlierThreshold","jerkOutlierMethod1","bigJerkness", ...
    "jerkOutlierMedian","jerkOutlierMoveMedian","jerkOutlierMean",...
    "jerkOutlierQuartiles","jerkOutlierGrubbs","jerkOutlierGesd",...
    "jerkOutlierThreshold");

toc;
end