% Author: Atanu Giri
% Date : 12/20/2022
% This function invokes the function 'entryExitTimeStampFun' and run on the id
% present in the 'input_data' file. The output file contains the runtime
% which is complementary to 'approachavoidtime' in live_table

function entryExitTimeStampOnInputArray(startRow,endRow)
tic;
% erf = @(id,varargin) deal(id,nan);

% startRow = 1000; endRow = 1005;
loadfile = load('input_data.mat');
input_data = loadfile.input_data;


[id,entryTime,exitTime,logicalApproach,distanceBeforeTone, ...
    velocityBeforeTone,distanceAfterTone,velocityAfterTone, ...
    distanceAfterToneUntilLimitingTimeStamp,velocityAfterToneUntilLimitingTimeStamp, ...
    distanceAfterToneUntilEntryTimeStamp,velocityAfterToneUntilEntryTimeStamp, ...
    distanceAfterEntryTimeStampUntilLimitingTimeStamp, ...
    velocityAfterEntryTimeStampUntilLimitingTimeStamp, ...
    distanceAfterExitTimeStamp,velocityAfterExitTimeStamp, ...
    distanceAfterExitTimeStampUntilLimitingTimeStamp, ...
    velocityAfterExitTimeStampUntilLimitingTimeStamp] = arrayfun(@(id) entryExitTimeStampFun(id), ...
    input_data.id(startRow:endRow),'UniformOutput',false,'ErrorHandler',@(S,id)entryExitTimeStampErrorHandler(S,id));

outputFileName = sprintf('entryExitTimeStamp_%dto%d',startRow,endRow);

save(outputFileName,"id","entryTime","exitTime","logicalApproach","distanceBeforeTone", ...
    "velocityBeforeTone","distanceAfterTone","velocityAfterTone", ...
    "distanceAfterToneUntilLimitingTimeStamp","velocityAfterToneUntilLimitingTimeStamp", ...
    "distanceAfterToneUntilEntryTimeStamp","velocityAfterToneUntilEntryTimeStamp", ...
    "distanceAfterEntryTimeStampUntilLimitingTimeStamp", ...
    "velocityAfterEntryTimeStampUntilLimitingTimeStamp", ...
    "distanceAfterExitTimeStamp","velocityAfterExitTimeStamp", ...
    "distanceAfterExitTimeStampUntilLimitingTimeStamp", ...
    "velocityAfterExitTimeStampUntilLimitingTimeStamp");

toc;
end